[project]
name = "personal-deadline-management-agent"
version = "0.1.0"
description = "Personal Deadline Management Agent - FastAPI application"
readme = "README.md"
authors = [
    { name = "Thuy Dung", email = "thuydungcolen2004@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "genai-core-shared==0.1.*",
    "genai-core-bedrock-llm==0.1.*",
    "sqlalchemy==2.0.43",
]

[dependency-groups]
dev = [
    "pytest>=8",
]

[[tool.uv.index]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/81909934/packages/pypi/simple/"

[tool.uv.sources]
genai-core-shared = { index = "gitlab" }
genai-core-bedrock-llm = { index = "gitlab" }

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
